### ISSUE TITLE
Colors + text styles on terminal output

### ISSUE THREAD

**Issue by urish** [TinyTapeout/tt-micropython-firmware#10]
A bunch of useful functions that enable prettier terminal output. I propose to include those in the SDK, so projects can use colors / text styles in their output:

```python
def bold(s):
    return f"\033[1m{s}\033[0m"

def underline(s):
    return f"\033[4m{s}\033[0m"

def inverse(s):
    return f"\033[7m{s}\033[0m"

def color(s, color, bright = True):
    COLORS = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    code= str(COLORS.index(color))
    suffix = ";1" if bright else ""
    return f"\033[3{code}{suffix}m{s}\033[0m"
```

These functions can be chained to combine styles.

Usage examples:

```python
print(f"I have to tell you something {bold('important')}!")
print(f"There was an {color('error', 'red')} in your input");
print(f"Here is how I combine {inverse(underline(color("multiple", "magenta")))} styles")
```

**Comment by psychogenic** [comment]
Nice.
Including.  Used in logging.  Added a global flag to module to disable (for writing out clean files or whatever)
![logout](https://github.com/user-attachments/assets/107380f1-2cea-4533-9334-31379f18bcb2)

**Comment by psychogenic** [comment]
> Did you forget to add a file?

Durp, yes.  Sorry about that.  

It actually wound up getting submitted as part of a commit in the TT06 branch I'm working on, https://github.com/TinyTapeout/tt-micropython-firmware/blob/tt06/src/ttboard/util/colors.py

I'm getting ready to merge that all into main and don't wanna deal with the conflict of having it in both, so get it above if you need it right away.
