### ISSUE TITLE
find command doesn't show indexes

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-micropython-firmware#20]
![image](https://github.com/user-attachments/assets/ce08e95c-c596-4130-9117-169b9a6d700b)

**Comment by mattvenn** [comment]
more context
![image](https://github.com/user-attachments/assets/534dc090-791a-4bfe-b7e2-cff2e765976f)

**Comment by psychogenic** [comment]
Solved with https://github.com/TinyTapeout/tt-micropython-firmware/commit/ff8cb7fcbfc58e6a73de31bf614119ec61f20c02

>>> tt.shuttle.find('second')
[<Design 109: tt_um_jeffdi_seven_segment_seconds (uninit)>, <Design 205: tt_um_mabhari_seven_segment_seconds (uninit)>, <Design 709: tt_um_seven_segment_seconds (uninit)>, <Design 162: tt_um_seven_segment_seconds_ksandov4 (uninit)>, <Design 199: tt_um_vhdl_seven_segment_seconds (uninit)>, <Design 192: wokwi_7_segment_seconds (uninit)>, <Design 32: wokwi_7_segment_seconds_verilog_demo (uninit)>]
>>> tt.shuttle[109]
<Design 109: tt_um_jeffdi_seven_segment_seconds>
>>>
