### ISSUE TITLE
can't report if a project works any more

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt-micropython-firmware#22]
![image](https://github.com/user-attachments/assets/8f72baa1-00db-403a-bf96-2e666cf2ffcd)

![image](https://github.com/user-attachments/assets/ff6b144e-e384-4a14-ab18-691b780debb1)

**Comment by psychogenic** [comment]
@urish : was does the commander app need to know a project/what has changed here?

**Comment by urish** [comment]
Fixed, it was a long standing bug in the submission app that affected a small number of projects (not related to SDK nor commander)
