### ISSUE TITLE
Create a file with tag name / commit sha in the generated UF2 firmware

### ISSUE THREAD

**Issue by urish** [TinyTapeout/tt-micropython-firmware#3]
This way, people can easily tell which version they have on their demo board. Inside the GitHub action, you can get the tag name from `${{  github.ref_name }}`

**Comment by psychogenic** [comment]
Augmented workflow to:

1. touch a file with the release tag in the name, so you can just:
>>> os.listdir()
['config.ini', ...  'release_v0.9.11c', 'shuttle_index.json', ...]

2. create UF2 files with actual versions, like tt-demo-rp2040-v0.9.11c.uf2
