### ISSUE TITLE
Migrate shuttle_index.json to the new tinytapeout-index format

### ISSUE THREAD

**Issue by urish** [TinyTapeout/tt-micropython-firmware#4]
The new format can be found at https://github.com/TinyTapeout/tinytapeout-index

There's also an API that allows retrieving just a subset of the info (which might be a good idea for the rp2040, as the flash space isn't plenty), e.g.: https://index.tinytapeout.com/tt04.json?fields=repo,address

**Comment by psychogenic** [comment]
[Project mux](https://github.com/TinyTapeout/tt-micropython-firmware/blob/main/src/ttboard/project_mux.py) now uses the new format, and the shuttle JSON file included was retrieved using https://index.tinytapeout.com/tt03p5.json?fields=repo,address,commit,clock_hz
