### ISSUE TITLE
TT04+ Hello (first boot operations)

### ISSUE THREAD

**Issue by urish** [TinyTapeout/tt-micropython-firmware#5]
Shouldn't this be bidir_byte?

https://github.com/TinyTapeout/tt-micropython-firmware/blob/78b711f9708479a7e1737a37c6c545db2a027200/src/ttboard/boot/firstboot_operations.py#L127

**Comment by psychogenic** [comment]
mmhm, that does seem to be the case.  Making sure...

**Comment by psychogenic** [comment]
Fixed with https://github.com/TinyTapeout/tt-micropython-firmware/commit/2c25cc0dd0af42b86448aecf340ee2963696b4ba
